export const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    // ▶ Project 1 – Royal Plaza
    {
      id: 101,
      name: "Royal Plaza – Hotel Booking",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-[15vh] left-[10vw]",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1011,
          name: "Royal Plaza.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Royal Plaza is a modern hotel booking platform built to make discovering and reserving stays feel effortless and premium.",
            "Instead of a basic listing site, it focuses on clean layouts, clear information, and smooth flows from browsing rooms to confirming bookings.",
            "The experience feels like exploring a curated hotel brand, with attention to visuals, copy, and user trust at every step.",
            "It is built with a modern TypeScript-based stack, emphasizing reusable components, performance, and scalable architecture.",
          ],
        },
        {
          id: 1012,
          name: "royal-plaza.live",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://github.com/prateekraiger/royal-plaza",
          position: "top-10 right-20",
        },
        {
          id: 1013,
          name: "royal-plaza.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/royal-plaza.png",
        },
        {
          id: 1014,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://royall-plaza.vercel.app/",
          position: "top-60 right-20",
        },
      ],
    },

    // ▶ Project 2 – Cote Royale
    {
      id: 102,
      name: "Cote Royale – Luxury Fragrance",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-[15vh] left-[30vw]",
      windowPosition: "top-[8vh] left-10",
      children: [
        {
          id: 1021,
          name: "Cote Royale.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Cote Royale is a luxury fragrance website designed to feel like an immersive high-end brand experience rather than a simple product catalog.",
            "It features an elegant dark theme, smooth animations, and carefully structured sections that guide users through stories, scents, and collections.",
            "The interface balances minimal typography with rich visuals, making the browsing experience feel cinematic and premium.",
            "Built with Next.js 15 and Prismic CMS, it combines performance, SEO-friendly routing, and flexible content management for future scalability.",
          ],
        },
        {
          id: 1022,
          name: "cote-royale.live",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://cote-royale-mu.vercel.app/", // repo link
          position: "top-10 right-20",
        },
        {
          id: 1023,
          name: "cote-royale.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "https://ik.imagekit.io/mtk2a0sx6/Screenshot%202025-09-06%20161132.png",
        },
        {
          id: 1024,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://ik.imagekit.io/mtk2a0sx6/Screenshot%202025-09-06%20161132.png",
          position: "top-60 right-20",
        },
      ],
    },

    // ▶ Project 3 – QuickHire
    {
      id: 103,
      name: "QuickHire – AI ATS",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-[15vh] left-[50vw]",
      windowPosition: "top-[11vh] left-16",
      children: [
        {
          id: 1031,
          name: "QuickHire.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "QuickHire is an AI-powered Applicant Tracking System designed to streamline how recruiters manage jobs, candidates, and hiring pipelines.",
            "Rather than just storing resumes, it organizes applications, supports filtered views, and makes it easier to track every step of the hiring process.",
            "The UI focuses on clarity and speed, giving a dashboard-like experience that feels familiar to modern SaaS HR tools.",
            "It is built with a JavaScript-based stack and modular components, making it ready to integrate AI workflows and external services over time.",
          ],
        },
        {
          id: 1032,
          name: "quickhire.app",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://github.com/prateekraiger/QuickHire",
          position: "top-10 right-20",
        },
        {
          id: 1033,
          name: "quickhire.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/quickhire.png",
        },
        {
          id: 1034,
          name: "Flow.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "/",
          position: "top-60 right-20",
        },
      ],
    },

    // ▶ Project 4 – StyleVerse
    {
      id: 104,
      name: "StyleVerse – E-commerce Platform",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-[15vh] left-[70vw]",
      windowPosition: "top-[6vh] left-32",
      children: [
        {
          id: 1041,
          name: "StyleVerse.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "StyleVerse is a modern e-commerce platform focused on delivering a smooth and intuitive shopping experience.",
            "It offers a clean product browsing flow, clear product detail pages, and streamlined cart interactions that feel responsive and fast.",
            "The interface is designed to feel like a contemporary fashion storefront, with emphasis on layout, spacing, and visual hierarchy.",
            "It is built with React and a JavaScript-based stack, using reusable components and state management to keep the UX snappy and consistent.",
          ],
        },
        {
          id: 1042,
          name: "styleverse.shop",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "/",
          position: "top-10 right-20",
        },
        {
          id: 1043,
          name: "styleverse.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/",
        },
        {
          id: 1044,
          name: "Wireframe.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "/",
          position: "top-60 right-20",
        },
      ],
    },

    // ▶ Project 5 – buildmeCV
    {
      id: 105,
      name: "buildmeCV – Resume Builder",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-[15vh] left-[90vw]",
      windowPosition: "top-[9vh] left-40",
      children: [
        {
          id: 1051,
          name: "buildmeCV.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "buildmeCV is a resume builder web application that helps users create clean, structured CVs without touching design tools.",
            "Instead of static templates, it uses form-driven inputs and live previews so users can see their CV take shape in real time.",
            "The experience is tuned for clarity and usability, making it easy for students, developers, and professionals to generate a polished resume quickly.",
            "It is built with TypeScript and a modern frontend stack, focusing on component reusability, maintainability, and a scalable codebase.",
          ],
        },
        {
          id: 1052,
          name: "buildmeCV.app",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://github.com/prateekraiger/buildmeCV",
          position: "top-10 right-20",
        },
        {
          id: 1053,
          name: "buildmeCV.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/buildmeCV.png",
        },
        {
          id: 1054,
          name: "Layout.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://pratik-me.pages.dev/",
          position: "top-60 right-20",
        },
      ],
    },
  ],
};
